//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


/// <reference path="../Models/TestModel.ts"/>
/// <reference path="../Models/Dummy.ts"/>
/// <reference path="../Models/New/FancyModel.ts"/>
import {TestModel} from "../../../../Reinforced/Typings/Test/Models/TestModel";
import {Dummy} from "../../../../Reinforced/Typings/Test/Models/Dummy";
import {FancyModel} from "../../../../Reinforced/Typings/Test/Models/New/FancyModel";
import {A, B} from "test";

@Injectable()
export class HomeController
{
	constructor (private http: Http) { } 
	public Index() : Observable<number>
	{
		var params = {  };
		return this.http.post('/Home/Index', params)
		    .map((r: Response) => r.json().data) as Observable<number>;
		
	}
	public Test() : Observable<TestModel>
	{
		var params = {  };
		return this.http.post('/Home/Test', params)
		    .map((r: Response) => r.json().data) as Observable<TestModel>;
		
	}
	public GetStr() : Observable<Dummy>
	{
		var params = {  };
		return this.http.post('/Home/GetStr', params)
		    .map((r: Response) => r.json().data) as Observable<Dummy>;
		
	}
	public FancyMethod(id: number) : Observable<FancyModel>
	{
		var params = { 'id': id };
		return this.http.post('/Home/FancyMethod', params)
		    .map((r: Response) => r.json().data) as Observable<FancyModel>;
		
	}
}
