//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


/// <reference path="../Models/Dummy.ts"/>
import {A, B} from "test";

import {Dummy} from "../../../../Reinforced/Typings/Test/Models/Dummy";
import {FancyModel} from "../../../../Reinforced/Typings/Test/Models/New/FancyModel";

@Injectable()
export class ValuesController
{
	constructor (private http: Http) { } 
	public Get() : Observable<Dummy>
	{
		var params = {  };
		return this.http.post('/Values/Get', params)
		    .map((r: Response) => r.json().data) as Observable<Dummy>;
		
	}
	public Get(id: number) : Observable<FancyModel[]>
	{
		var params = { 'id': id };
		return this.http.post('/Values/Get', params)
		    .map((r: Response) => r.json().data) as Observable<FancyModel[]>;
		
	}
}

