//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


/// <reference path="../Models/ITestModel.ts"/>
/// <reference path="../Models/Dummy.ts"/>
import {Dummy} from "../../../../Reinforced/Typings/Test/Models";

import {A, B} from "test";

@Injectable()
export class HomeController
{
	constructor (private http: Http) { } 
	public Index() : Observable<number>
	{
		var params = {  };
		return this.http.post('/Home/Index', params)
		    .map((r: Response) => r.json().data) as Observable<number>;
		
	}
	public Test() : Observable<ITestModel>
	{
		var params = {  };
		return this.http.post('/Home/Test', params)
		    .map((r: Response) => r.json().data) as Observable<ITestModel>;
		
	}
	public GetStr() : Observable<Dummy>
	{
		var params = {  };
		return this.http.post('/Home/GetStr', params)
		    .map((r: Response) => r.json().data) as Observable<Dummy>;
		
	}
}
