//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


/// <reference path="ITestModel.ts"/>
import {ITestModel} from "../../../../Reinforced/Typings/Test/Models/ITestModel";
export class Dummy

{
	public Test: ITestModel;
}

