//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


/// <reference path="TestModel.ts"/>
import {TestModel} from "../../../../Reinforced/Typings/Test/Models/TestModel";
import {TestModel} from "../../../../Reinforced/Typings/Test/Models/TestModel";

export class Dummy
{
	public Test: TestModel;
}

