//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


/// <reference path="FancyModel.ts"/>
import {FancyModel} from "../../../../../Reinforced/Typings/Test/Models/New/FancyModel";

export class ExtendedFancyModel extends FancyModel
{
	public NewFancyProperty: string;
}

