//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


import {Dummy} from "../../../../../Reinforced/Typings/Test/Models/Dummy";

export class FancyModel
{
	public One: number;
	public Two: string[];
	public Zero: boolean;
	public Dummy: Dummy[];
}

